OBJS	= System/FalconRockets/FalconHeavy.o System/FalconRockets/FalconHeavyBuilder.o System/FalconRockets/FalconHeavyCreator.o System/FalconRockets/FalconNine.o System/FalconRockets/FalconNineBuilder.o System/FalconRockets/FalconNineCreator.o System/FalconRockets/InterStage.o System/FalconRockets/InterStageCreator.o System/FalconRockets/LandState.o System/FalconRockets/LaunchState.o System/FalconRockets/main.o System/FalconRockets/Rocket.o System/FalconRockets/RocketBuilder.o System/FalconRockets/RocketBuilderDirector.o System/FalconRockets/RocketFactory.o System/FalconRockets/RocketState.o System/FalconRockets/SeparationState.o System/FalconRockets/Spacecraft.o System/FalconRockets/Stage.o System/FalconRockets/StageFactory.o System/FalconRockets/StageTwoCreator.o System/FalconRockets/VacuumCreator.o System/FalconRockets/VacuumEngine.o
SOURCE	= System/FalconRockets/FalconHeavy.cpp System/FalconRockets/FalconHeavyBuilder.cpp System/FalconRockets/FalconHeavyCreator.cpp System/FalconRockets/FalconNine.cpp System/FalconRockets/FalconNineBuilder.cpp System/FalconRockets/FalconNineCreator.cpp System/FalconRockets/InterStage.cpp System/FalconRockets/InterStageCreator.cpp System/FalconRockets/LandState.cpp System/FalconRockets/LaunchState.cpp System/FalconRockets/main.cpp System/FalconRockets/Rocket.cpp System/FalconRockets/RocketBuilder.cpp System/FalconRockets/RocketBuilderDirector.cpp System/FalconRockets/RocketFactory.cpp System/FalconRockets/RocketState.cpp System/FalconRockets/SeparationState.cpp System/FalconRockets/Spacecraft.cpp System/FalconRockets/Stage.cpp System/FalconRockets/StageFactory.cpp System/FalconRockets/StageTwoCreator.cpp System/FalconRockets/VacuumCreator.cpp System/FalconRockets/VacuumEngine.cpp
HEADER	= System/FalconRockets/Engine.h System/FalconRockets/FalconHeavy.h System/FalconRockets/FalconHeavyBuilder.h System/FalconRockets/FalconHeavyCreator.h System/FalconRockets/FalconNine.h System/FalconRockets/FalconNineBuilder.h System/FalconRockets/FalconNineCreator.h System/FalconRockets/InterStage.h System/FalconRockets/InterStageCreator.h System/FalconRockets/LandState.h System/FalconRockets/LaunchState.h System/FalconRockets/Rocket.h System/FalconRockets/RocketBuilder.h System/FalconRockets/RocketBuilderDirector.h System/FalconRockets/RocketFactory.h System/FalconRockets/RocketState.h System/FalconRockets/SeparationState.h System/FalconRockets/Spacecraft.h System/FalconRockets/Stage.h System/FalconRockets/StageOne.h System/FalconRockets/StageTwo.h System/FalconRockets/StageFactory.h System/FalconRockets/StageTwoCreator.h System/FalconRockets/VacuumCreator.h System/FalconRockets/VacuumEngine.h
OUT	= a.out
CC	 = g++
FLAGS	 = -g -c -Wall
LFLAGS	 = 

all: $(OBJS)
	$(CC) -g $(OBJS) -o $(OUT) $(LFLAGS)

System/FalconRockets/FalconHeavy.o: System/FalconRockets/FalconHeavy.cpp
	$(CC) $(FLAGS) System/FalconRockets/FalconHeavy.cpp 

System/FalconRockets/FalconHeavyBuilder.o: System/FalconRockets/FalconHeavyBuilder.cpp
	$(CC) $(FLAGS) System/FalconRockets/FalconHeavyBuilder.cpp 

System/FalconRockets/FalconHeavyCreator.o: System/FalconRockets/FalconHeavyCreator.cpp
	$(CC) $(FLAGS) System/FalconRockets/FalconHeavyCreator.cpp 

System/FalconRockets/FalconNine.o: System/FalconRockets/FalconNine.cpp
	$(CC) $(FLAGS) System/FalconRockets/FalconNine.cpp 

System/FalconRockets/FalconNineBuilder.o: System/FalconRockets/FalconNineBuilder.cpp
	$(CC) $(FLAGS) System/FalconRockets/FalconNineBuilder.cpp 

System/FalconRockets/FalconNineCreator.o: System/FalconRockets/FalconNineCreator.cpp
	$(CC) $(FLAGS) System/FalconRockets/FalconNineCreator.cpp 

System/FalconRockets/InterStage.o: System/FalconRockets/InterStage.cpp
	$(CC) $(FLAGS) System/FalconRockets/InterStage.cpp 

System/FalconRockets/InterStageCreator.o: System/FalconRockets/InterStageCreator.cpp
	$(CC) $(FLAGS) System/FalconRockets/InterStageCreator.cpp 

System/FalconRockets/LandState.o: System/FalconRockets/LandState.cpp
	$(CC) $(FLAGS) System/FalconRockets/LandState.cpp 

System/FalconRockets/LaunchState.o: System/FalconRockets/LaunchState.cpp
	$(CC) $(FLAGS) System/FalconRockets/LaunchState.cpp 

System/FalconRockets/main.o: System/FalconRockets/main.cpp
	$(CC) $(FLAGS) System/FalconRockets/main.cpp 

System/FalconRockets/Rocket.o: System/FalconRockets/Rocket.cpp
	$(CC) $(FLAGS) System/FalconRockets/Rocket.cpp 

System/FalconRockets/RocketBuilder.o: System/FalconRockets/RocketBuilder.cpp
	$(CC) $(FLAGS) System/FalconRockets/RocketBuilder.cpp 

System/FalconRockets/RocketBuilderDirector.o: System/FalconRockets/RocketBuilderDirector.cpp
	$(CC) $(FLAGS) System/FalconRockets/RocketBuilderDirector.cpp 

System/FalconRockets/RocketFactory.o: System/FalconRockets/RocketFactory.cpp
	$(CC) $(FLAGS) System/FalconRockets/RocketFactory.cpp 

System/FalconRockets/RocketState.o: System/FalconRockets/RocketState.cpp
	$(CC) $(FLAGS) System/FalconRockets/RocketState.cpp 

System/FalconRockets/SeparationState.o: System/FalconRockets/SeparationState.cpp
	$(CC) $(FLAGS) System/FalconRockets/SeparationState.cpp 

System/FalconRockets/Spacecraft.o: System/FalconRockets/Spacecraft.cpp
	$(CC) $(FLAGS) System/FalconRockets/Spacecraft.cpp 

System/FalconRockets/Stage.o: System/FalconRockets/Stage.cpp
	$(CC) $(FLAGS) System/FalconRockets/Stage.cpp 

System/FalconRockets/StageFactory.o: System/FalconRockets/StageFactory.cpp
	$(CC) $(FLAGS) System/FalconRockets/StageFactory.cpp 

System/FalconRockets/StageTwoCreator.o: System/FalconRockets/StageTwoCreator.cpp
	$(CC) $(FLAGS) System/FalconRockets/StageTwoCreator.cpp 

System/FalconRockets/VacuumCreator.o: System/FalconRockets/VacuumCreator.cpp
	$(CC) $(FLAGS) System/FalconRockets/VacuumCreator.cpp 

System/FalconRockets/VacuumEngine.o: System/FalconRockets/VacuumEngine.cpp
	$(CC) $(FLAGS) System/FalconRockets/VacuumEngine.cpp 


clean:
	rm -f $(OBJS) $(OUT)

run: $(OUT)
	./$(OUT)