main:
	g++ -g -std=c++11 DragonSpacecraft/*.cpp DragonSpacecraft/*.h  LaunchSimulator/*.h LaunchSimulator/*.cpp StarlinkSatellites/*.h StarlinkSatellites/*.cpp FalconRockets/*.h FalconRockets/*.cpp *.cpp -o main
run:	main
	./main

clean:
	rm main